version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
  - package_manager: 'ruby'
    directory: '/docs'
    update_schedule: 'live'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'