title: JSVerbalExpressions Docs
description: API Documentation for JSVerbalExpressions.
repository: VerbalExpressions/JSVerbalExpressions

show_downloads: true

theme: jekyll-theme-minimal

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore

cdn_url: https://jsdelivr.com/package/npm/verbal-expressions
npm_url: https://npmjs.com/package/verbal-expressions
minified_url: https://cdn.jsdelivr.net/npm/verbal-expressions@latest/dist/verbalexpressions.min.js

